site_name: dbdaora
site_description: |
  Communicates with databases using repository and
  service patterns and python dataclasses

theme:
    name: material
    custom_dir: theme
    palette:
      primary: deep-purple
      accent: grey
    logo: dbdaora.svg
    favicon: favicon.png

repo_name: dutradda/dbdaora
repo_url: https://github.com/dutradda/dbdaora
edit_uri: ''

nav:
    - dbdaora: index.md
    - Domain Model Example: domain-model/simple.md
    - Typed Dict Entity: typed-dict.md
    # - Features: 'features.md'
    # - Repository pattern intro: 'repository-pattern.md'
    # - Alternatives, Inspiration and Comparisons: 'alternatives.md'
    # - History, Design and Future: 'history-design-future.md'
    # - External Links and Articles: 'external-links.md'
    # - Benchmarks: 'benchmarks.md'
    - Development - Contributing: contributing.md
    - Changelog: changelog.md

markdown_extensions:
    - markdown_include.include:
        base_path: docs
    - codehilite:
        guess_lang: false

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
