site_name: dataclassdb
site_description: Generates SQL and NoSQL Database Models from @dataclass

theme:
    name: 'material'
    palette:
      primary: 'teal'
      accent: 'amber'
    logo: 'img/icon-white.svg'
    favicon: 'img/favicon.png'

repo_name: dutradda/dataclassdb
repo_url: https://github.com/dutradda/dataclassdb
edit_uri: ''
google_analytics:
    - ''
    - 'auto'

nav:
    - FastAPI: 'index.md'
    - Features: 'features.md'
    - \@dataclass intro: 'dataclass.md'
    - Tutorial - User Guide:
        - Introduciton: 'tutorial/intro.md'
        - First Steps: 'tutorial/first-steps.md'
        - Path Parameters: 'tutorial/path-params.md'
        - Dependencies:
            - First Steps: 'tutorial/dependencies/first-steps.md'
            - Classes as Dependencies: 'tutorial/dependencies/classes-as-dependencies.md'
        - Security: 
            - Security Intro: 'tutorial/security/intro.md'
            - First Steps: 'tutorial/security/first-steps.md'
        - Middleware: 'tutorial/middleware.md'    
    - Concurrency and async / await: 'async.md'
    - Alternatives, Inspiration and Comparisons: 'alternatives.md'
    - History, Design and Future: 'history-design-future.md'
    - External Links and Articles: 'external-links.md'
    - Benchmarks: 'benchmarks.md'
    - Help FastAPI - Get Help: 'help-fastapi.md'
    - Development - Contributing: 'contributing.md'
    - Release Notes: release-notes.md

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra
